import read_data_from_file
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QTableWidgetItem
import sys
import funcs
import time
import threading


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.frame.setFont(font)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.frame_3.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 400))
        self.frame_4.setStyleSheet("background-color: black;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(150, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_58 = QtWidgets.QFrame(self.frame_7)
        self.frame_58.setMinimumSize(QtCore.QSize(130, 0))
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.label = QtWidgets.QLabel(self.frame_58)
        self.label.setGeometry(QtCore.QRect(0, 0, 131, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("rsh.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.frame_58)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet(" background-color: #3498db; \n"
"            color: white;\n"
"            padding: 10px;\n"
"           ")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setStyleSheet(" background-color: #3498db; \n"
"            color: white;\n"
"            padding: 10px;\n"
"           ")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_2 = QtWidgets.QLabel(self.frame_14)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.frame_14)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setGeometry(QtCore.QRect(-20, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_20 = QtWidgets.QFrame(self.frame_11)
        self.frame_20.setStyleSheet("\n"
" background-color: #3498db; /* Light Blue */\n"
"            color: white;\n"
"            padding: 10px;\n"
"          ")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_2.addWidget(self.frame_20)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setStyleSheet(" background-color: #3498db; /* Light Blue */\n"
"            color: white;\n"
"            padding: 10px;\n"
"         ")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setMinimumSize(QtCore.QSize(640, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: #FFB6C1;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(30, 30))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_42 = QtWidgets.QFrame(self.tab_3)
        self.frame_42.setStyleSheet("background-color: #000080;")
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_81 = QtWidgets.QFrame(self.frame_42)
        self.frame_81.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_81.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.frame_81.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_81.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_81.setObjectName("frame_81")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_81)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_44 = QtWidgets.QFrame(self.frame_81)
        self.frame_44.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_44.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_44.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_47 = QtWidgets.QFrame(self.frame_44)
        self.frame_47.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_47)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_48 = QtWidgets.QFrame(self.frame_47)
        self.frame_48.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_48.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_48.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"")
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_49 = QtWidgets.QFrame(self.frame_48)
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.horizontalLayout_6.addWidget(self.frame_49)
        self.frame_50 = QtWidgets.QFrame(self.frame_48)
        self.frame_50.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.searching_categoty = QtWidgets.QComboBox(self.frame_50)
        self.searching_categoty.setGeometry(QtCore.QRect(0, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.searching_categoty.setFont(font)
        self.searching_categoty.setObjectName("searching_categoty")
        #self.searching_categoty.currentTextChanged.connect(self.onsearching_category_change)
        self.searching_categoty.addItem("")
        self.horizontalLayout_6.addWidget(self.frame_50)
        self.frame_51 = QtWidgets.QFrame(self.frame_48)
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.horizontalLayout_6.addWidget(self.frame_51)
        self.frame_52 = QtWidgets.QFrame(self.frame_48)
        self.frame_52.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.searching_algorithm = QtWidgets.QComboBox(self.frame_52)
        self.searching_algorithm.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.searching_algorithm.setFont(font)
        self.searching_algorithm.setStyleSheet("")
        self.searching_algorithm.setObjectName("searching_algorithm")
        self.searching_algorithm.addItem("")
        self.searching_algorithm.addItem("")
        #self.searching_algorithm.currentTextChanged.connect(self.enableentity1)
        self.horizontalLayout_6.addWidget(self.frame_52)
        self.frame_53 = QtWidgets.QFrame(self.frame_48)
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_6.addWidget(self.frame_53)
        self.frame_54 = QtWidgets.QFrame(self.frame_48)
        self.frame_54.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.searching_entity1 = QtWidgets.QComboBox(self.frame_54)
        self.searching_entity1.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.searching_entity1.setFont(font)
        self.searching_entity1.setObjectName("searching_entity1")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.searching_entity1.addItem("")
        self.horizontalLayout_6.addWidget(self.frame_54)
        self.frame_55 = QtWidgets.QFrame(self.frame_48)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.horizontalLayout_6.addWidget(self.frame_55)
        self.frame_60 = QtWidgets.QFrame(self.frame_48)
        self.frame_60.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.searching_lineEdit = QtWidgets.QLineEdit(self.frame_60)
        self.searching_lineEdit.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searching_lineEdit.setFont(font)
        self.searching_lineEdit.setObjectName("searching_lineEdit")
        #self.searching_lineEdit.textChanged.connect(self.lineedittextchange)
        self.horizontalLayout_6.addWidget(self.frame_60)
        self.frame_91 = QtWidgets.QFrame(self.frame_48)
        self.frame_91.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_91.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_91.setObjectName("frame_91")
        self.horizontalLayout_6.addWidget(self.frame_91)
        self.horizontalLayout_14.addWidget(self.frame_48)
        self.verticalLayout_8.addWidget(self.frame_47)
        self.frame_46 = QtWidgets.QFrame(self.frame_44)
        self.frame_46.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_46)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_61 = QtWidgets.QFrame(self.frame_46)
        self.frame_61.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_61.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_61.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"")
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_61)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_72 = QtWidgets.QFrame(self.frame_61)
        self.frame_72.setStyleSheet("background-color: rgb(113, 113, 113);")
        self.frame_72.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_72.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_72.setObjectName("frame_72")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_72)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_73 = QtWidgets.QFrame(self.frame_72)
        self.frame_73.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_73.setObjectName("frame_73")
        self.searching_filters = QtWidgets.QComboBox(self.frame_73)
        self.searching_filters.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.searching_filters.setFont(font)
        self.searching_filters.setObjectName("searching_filters")
        self.searching_filters.addItem("")
        self.searching_filters.addItem("")
        self.searching_filters.addItem("")
        self.searching_filters.addItem("")
        self.horizontalLayout_13.addWidget(self.frame_73)
        self.frame_80 = QtWidgets.QFrame(self.frame_72)
        self.frame_80.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_80.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_80.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_80.setObjectName("frame_80")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_80)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_57 = QtWidgets.QFrame(self.frame_80)
        self.frame_57.setMinimumSize(QtCore.QSize(90, 0))
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.Searching_start_btn = QtWidgets.QPushButton(self.frame_57)
        self.Searching_start_btn.setGeometry(QtCore.QRect(30, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Searching_start_btn.setFont(font)
        self.Searching_start_btn.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius:10\n"
"")
        self.Searching_start_btn.clicked.connect(self.Buttonevent)
        self.Searching_start_btn.setObjectName("Searching_start_btn")        
        #self.searching_lineEdit.textChanged.connect(self.lineedittextchange)
        self.horizontalLayout_10.addWidget(self.frame_57)
        self.frame_63 = QtWidgets.QFrame(self.frame_80)
        self.frame_63.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.label_4 = QtWidgets.QLabel(self.frame_63)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 70, 31))
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.frame_63)
        self.frame_64 = QtWidgets.QFrame(self.frame_80)
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.horizontalLayout_10.addWidget(self.frame_64)
        self.horizontalLayout_13.addWidget(self.frame_80)
        self.frame_82 = QtWidgets.QFrame(self.frame_72)
        self.frame_82.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_82.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_82.setObjectName("frame_82")
        self.horizontalLayout_13.addWidget(self.frame_82)
        self.horizontalLayout_12.addWidget(self.frame_72)
        self.horizontalLayout_15.addWidget(self.frame_61)
        self.verticalLayout_8.addWidget(self.frame_46)
        self.verticalLayout_6.addWidget(self.frame_44)
        self.frame_45 = QtWidgets.QFrame(self.frame_81)
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_45)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.frame_86 = QtWidgets.QFrame(self.frame_45)
        self.frame_86.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_86.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_86.setObjectName("frame_86")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_86)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.Searching_tableWidget = QtWidgets.QTableWidget(self.frame_86)
        self.Searching_tableWidget.setStyleSheet("background-color: #ADD8E6;\n"
"    ")
        self.Searching_tableWidget.setObjectName("Searching_tableWidget")
        self.Searching_tableWidget.setColumnCount(10)
        self.Searching_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0))
        self.Searching_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Searching_tableWidget.setHorizontalHeaderItem(9, item)
        self.horizontalLayout_19.addWidget(self.Searching_tableWidget)
        self.horizontalLayout_18.addWidget(self.frame_86)
        self.verticalLayout_6.addWidget(self.frame_45)
        self.verticalLayout_7.addWidget(self.frame_81)
        self.gridLayout_5.addWidget(self.frame_42, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_19 = QtWidgets.QFrame(self.tab_2)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_43 = QtWidgets.QFrame(self.frame_19)
        self.frame_43.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_43.setStyleSheet("background-color: rgb(170, 170, 170);")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_22 = QtWidgets.QFrame(self.frame_43)
        self.frame_22.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_22.setStyleSheet("background-color: rgb(113, 113, 113);\n"
"")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_31 = QtWidgets.QFrame(self.frame_22)
        self.frame_31.setStyleSheet("")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_31)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_33 = QtWidgets.QFrame(self.frame_31)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_5.addWidget(self.frame_33)
        self.frame_38 = QtWidgets.QFrame(self.frame_31)
        self.frame_38.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.Sorting_category = QtWidgets.QComboBox(self.frame_38)
        self.Sorting_category.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Sorting_category.setFont(font)
        self.Sorting_category.setObjectName("Sorting_category")
        self.Sorting_category.currentTextChanged.connect(self.category_change)
        self.Sorting_category.addItem("")
        self.horizontalLayout_5.addWidget(self.frame_38)
        self.frame_34 = QtWidgets.QFrame(self.frame_31)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_5.addWidget(self.frame_34)
        self.frame_35 = QtWidgets.QFrame(self.frame_31)
        self.frame_35.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.Sorting_algorithm = QtWidgets.QComboBox(self.frame_35)
        self.Sorting_algorithm.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.Sorting_algorithm.setFont(font)
        self.Sorting_algorithm.setStyleSheet("")
        self.Sorting_algorithm.setObjectName("Sorting_algorithm")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.Sorting_algorithm.addItem("")
        self.horizontalLayout_5.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_31)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_5.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_31)
        self.frame_37.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.sorting_order = QtWidgets.QComboBox(self.frame_37)
        self.sorting_order.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.sorting_order.setFont(font)
        self.sorting_order.setObjectName("sorting_order")
        self.sorting_order.addItem("")
        self.sorting_order.addItem("")
        self.sorting_order.addItem("")
        self.horizontalLayout_5.addWidget(self.frame_37)
        self.frame_39 = QtWidgets.QFrame(self.frame_31)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_5.addWidget(self.frame_39)
        self.verticalLayout_11.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_22)
        self.frame_32.setStyleSheet("")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_83 = QtWidgets.QFrame(self.frame_32)
        self.frame_83.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_83.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_83.setObjectName("frame_83")
        self.horizontalLayout_7.addWidget(self.frame_83)
        self.frame_40 = QtWidgets.QFrame(self.frame_32)
        self.frame_40.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.sorting_entity = QtWidgets.QComboBox(self.frame_40)
        self.sorting_entity.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.sorting_entity.setFont(font)
        self.sorting_entity.setObjectName("sorting_entity")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.sorting_entity.addItem("")
        self.horizontalLayout_7.addWidget(self.frame_40)
        self.frame_41 = QtWidgets.QFrame(self.frame_32)
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.horizontalLayout_7.addWidget(self.frame_41)
        self.frame_65 = QtWidgets.QFrame(self.frame_32)
        self.frame_65.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.Sorting_start_btn = QtWidgets.QPushButton(self.frame_65)
        self.Sorting_start_btn.setGeometry(QtCore.QRect(80, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sorting_start_btn.setFont(font)
        self.Sorting_start_btn.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius:10\n"
"")
        self.Sorting_start_btn.setObjectName("Sorting_start_btn")
        self.Sorting_start_btn.clicked.connect(self.start)
        self.horizontalLayout_7.addWidget(self.frame_65)
        self.frame_69 = QtWidgets.QFrame(self.frame_32)
        self.frame_69.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_69.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_69.setObjectName("frame_69")
        self.label_10 = QtWidgets.QLabel(self.frame_69)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.label_10.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.frame_69)
        self.frame_68 = QtWidgets.QFrame(self.frame_32)
        self.frame_68.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_68.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_68.setObjectName("frame_68")
        self.horizontalLayout_7.addWidget(self.frame_68)
        self.frame_67 = QtWidgets.QFrame(self.frame_32)
        self.frame_67.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_67.setObjectName("frame_67")
        self.horizontalLayout_7.addWidget(self.frame_67)
        self.verticalLayout_11.addWidget(self.frame_32)
        self.verticalLayout_10.addWidget(self.frame_22)
        self.frame_66 = QtWidgets.QFrame(self.frame_43)
        self.frame_66.setMinimumSize(QtCore.QSize(90, 0))
        self.frame_66.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_66.setObjectName("frame_66")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_66)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_66)
        self.tableWidget.setStyleSheet("background-color: #ADD8E6;\n"
"    ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.frame_66)
        self.verticalLayout_4.addWidget(self.frame_43)
        self.gridLayout_4.addWidget(self.frame_19, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout_5.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "RSH"))
        self.label_3.setText(_translate("MainWindow", "      E-Shopping"))
        self.label_5.setText(_translate("MainWindow", "     Junction"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Sorting</p></body></html>"))
        self.searching_categoty.setItemText(0, _translate("MainWindow", "RSH E-Shopping Junction"))
        self.searching_algorithm.setItemText(0, _translate("MainWindow", "Select Algorithm"))
        self.searching_algorithm.setItemText(1, _translate("MainWindow", "Linear Search"))
        self.searching_entity1.setItemText(0, _translate("MainWindow", "Select First Entitiy"))
        self.searching_entity1.setItemText(1, _translate("MainWindow", "Type Of Product"))
        self.searching_entity1.setItemText(2, _translate("MainWindow", "Name Of Product"))
        self.searching_entity1.setItemText(3, _translate("MainWindow", "Brand Name"))
        self.searching_entity1.setItemText(4, _translate("MainWindow", "Out Of Stock"))
        self.searching_entity1.setItemText(5, _translate("MainWindow", "Price Of Products"))
        self.searching_entity1.setItemText(6, _translate("MainWindow", "Discount On Product"))
        self.searching_entity1.setItemText(7, _translate("MainWindow", "Delivery Charges"))
        self.searching_entity1.setItemText(8, _translate("MainWindow", "Sold Products"))
        self.searching_entity1.setItemText(9, _translate("MainWindow", "Ratings"))
        self.searching_lineEdit.setText(_translate("MainWindow", "Search"))
        self.searching_filters.setItemText(0, _translate("MainWindow", "Filter By"))
        self.searching_filters.setItemText(1, _translate("MainWindow", "Contains"))
        self.searching_filters.setItemText(2, _translate("MainWindow", "Starts With"))
        self.searching_filters.setItemText(3, _translate("MainWindow", "Ends With"))
        self.Searching_start_btn.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "0.0s"))
        item = self.Searching_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.Searching_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.Searching_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.Searching_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "D"))
        item = self.Searching_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E"))
        item = self.Searching_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "F"))
        item = self.Searching_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "G"))
        item = self.Searching_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "H"))
        item = self.Searching_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "I"))
        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Searching"))
        self.Sorting_category.setItemText(0, _translate("MainWindow", "RSH E-Shopping Junction"))
        self.Sorting_algorithm.setItemText(0, _translate("MainWindow", "Select Algorithm"))
        self.Sorting_algorithm.setItemText(1, _translate("MainWindow", "Bubble Sort"))
        self.Sorting_algorithm.setItemText(2, _translate("MainWindow", "Insertion Sort"))
        self.Sorting_algorithm.setItemText(3, _translate("MainWindow", "Selection Sort"))
        self.Sorting_algorithm.setItemText(4, _translate("MainWindow", "Merge Sort"))
        self.Sorting_algorithm.setItemText(5, _translate("MainWindow", "Quick Sort"))
        self.Sorting_algorithm.setItemText(6, _translate("MainWindow", "Counting Sort"))
        self.Sorting_algorithm.setItemText(7, _translate("MainWindow", "Bucket Sort"))
        self.Sorting_algorithm.setItemText(8, _translate("MainWindow", "Radix Sort"))
        self.sorting_order.setItemText(0, _translate("MainWindow", "Select Order"))
        self.sorting_order.setItemText(1, _translate("MainWindow", "Increasing"))
        self.sorting_order.setItemText(2, _translate("MainWindow", "Decreasing"))
        self.sorting_entity.setItemText(0, _translate("MainWindow", "Select Entitiy"))
        self.sorting_entity.setItemText(1, _translate("MainWindow", "Type Of Product"))
        self.sorting_entity.setItemText(2, _translate("MainWindow", "Name Of Product"))
        self.sorting_entity.setItemText(3, _translate("MainWindow", "Brand Name"))
        self.sorting_entity.setItemText(4, _translate("MainWindow", "Out Of Stock"))
        self.sorting_entity.setItemText(5, _translate("MainWindow", "Price Of products"))
        self.sorting_entity.setItemText(6, _translate("MainWindow", "Discount On Product"))
        self.sorting_entity.setItemText(7, _translate("MainWindow", "Delivery Charges"))
        self.sorting_entity.setItemText(8, _translate("MainWindow", "Sold Products"))
        self.sorting_entity.setItemText(9, _translate("MainWindow", "Ratings"))
        self.Sorting_start_btn.setText(_translate("MainWindow", "Start"))
        self.label_10.setText(_translate("MainWindow", "0.0s"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type Of Product"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name Of Product"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Brand Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Out Of Stock"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price Of products"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Discount On Product"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Delivery Charges"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Sold Products"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Ratings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sorting"))
    
    def category_textchg(self,text):
        if(text == "RSH E-Shopping Junction"):
            self.sorting_entity.clear()
            self.sorting_entity.addItem("Select Entity")
            self.sorting_entity.addItem("Type Of Product")
            self.sorting_entity.addItem("Name Of Product")
            self.sorting_entity.addItem("Brand Name")
            self.sorting_entity.addItem("Out Of Stock")
            self.sorting_entity.addItem("Price Of products")
            self.sorting_entity.addItem("Discount On Product")
            self.sorting_entity.addItem("Delivery Charges")
            self.sorting_entity.addItem("Sold Products")
            self.sorting_entity.addItem("Ratings")
            row =0
            self.tableWidget.setColumnCount(9)
            self.tableWidget.setRowCount(len(read_data_from_file.eBay))
            self.tableWidget.setHorizontalHeaderLabels(["Type Of Product","Name Of product","Brand Name","Out Of Stock","Price Of Products","Discount On Product","Delivery Charges","Sold Products","Ratings"])
            for a in read_data_from_file.eBay:
                self.tableWidget.setItem(row,0,QTableWidgetItem(str(a['Type Of Product'])))
                self.tableWidget.setItem(row,1,QTableWidgetItem(str(a['Name Of Product'])))
                self.tableWidget.setItem(row,2,QTableWidgetItem(str(a['Brand Name'])))
                self.tableWidget.setItem(row,3,QTableWidgetItem(str(a['Out Of Stock'])))
                self.tableWidget.setItem(row,4,QTableWidgetItem(str(a['Price Of products'])))
                self.tableWidget.setItem(row,5,QTableWidgetItem(str(a['Discount On Product'])))
                self.tableWidget.setItem(row,6,QTableWidgetItem(str(a['Delivery Charges'])))
                self.tableWidget.setItem(row,7,QTableWidgetItem(str(a['Sold Products'])))
                self.tableWidget.setItem(row,8,QTableWidgetItem(str(a['Ratings'])))
                row += 1
            self.searching_entity1.clear()
            self.searching_entity1.addItem("Select Entity")
            self.searching_entity1.addItem("Type Of Product")
            self.searching_entity1.addItem("Name Of Product")
            self.searching_entity1.addItem("Brand Name")
            self.searching_entity1.addItem("Out Of Stock")
            self.searching_entity1.addItem("Price Of Products")
            self.searching_entity1.addItem("Discount On Product")
            self.searching_entity1.addItem("Delivery Charges")
            self.searching_entity1.addItem("Sold Products")
            self.searching_entity1.addItem("Ratings")
            row =0
            self.Searching_tableWidget.setColumnCount(9)
            self.Searching_tableWidget.setRowCount(len(read_data_from_file.eBay))
            self.Searching_tableWidget.setHorizontalHeaderLabels(["Type Of Product","Name Of Product","Brand Name","Out Of Stock","Price Of Products","Discount On Product","Delivery Charges","Sold Products","Ratings"])
            for a in read_data_from_file.eBay:
                self.Searching_tableWidget.setItem(row,0,QTableWidgetItem(str(a['Type Of Product'])))
                self.Searching_tableWidget.setItem(row,1,QTableWidgetItem(str(a['Name Of Product'])))
                self.Searching_tableWidget.setItem(row,2,QTableWidgetItem(str(a['Brand Name'])))
                self.Searching_tableWidget.setItem(row,3,QTableWidgetItem(str(a['Out Of Stock'])))
                self.Searching_tableWidget.setItem(row,4,QTableWidgetItem(str(a['Price Of products'])))
                self.Searching_tableWidget.setItem(row,5,QTableWidgetItem(str(a['Discount On Product'])))
                self.Searching_tableWidget.setItem(row,6,QTableWidgetItem(str(a['Delivery Charges'])))
                self.Searching_tableWidget.setItem(row,7,QTableWidgetItem(str(a['Sold Products'])))
                self.Searching_tableWidget.setItem(row,8,QTableWidgetItem(str(a['Ratings'])))
                row += 1
        
    def category_change(self,text):
        Temp=threading.Thread(target=self.category_textchg(text))
        Temp.start()
    
    def start(self,count):
        #self.Searching_start_btn.clicked.connect(self.searching)
        global Previous
        entity_Text = str(self.sorting_entity.currentText())
        algorithm_Text = str(self.Sorting_algorithm.currentText())
        category_Text = str(self.Sorting_category.currentText())
        order_Text = str(self.sorting_order.currentText())
        array=[]
        if(category_Text == "RSH E-Shopping Junction"):
            array = read_data_from_file.eBay
        if(algorithm_Text != "Select Algorithm" and entity_Text != "Select Entitiy" and order_Text != "Select Order"):
            start_time = time.time()
            if(algorithm_Text == "Bubble Sort"):
                array=funcs.BubbleSort(array,0,len(array),entity_Text)
            elif(algorithm_Text == "Insertion Sort"):
                array = funcs.InsertionSort(array, 0, len(array), entity_Text)
            elif(algorithm_Text == "Selection Sort"):
                array = funcs.SelectionSort(array, 0, len(array), entity_Text)
            elif(algorithm_Text == "Merge Sort"):
                array = funcs.MergeSort(array, 0, len(array), entity_Text)
            elif(algorithm_Text == "Quick Sort"):
                array = funcs.QuickSort(array, 0, len(array)-1, entity_Text)
            elif(algorithm_Text == "Counting Sort"):
                array=funcs.CountingSort(array,entity_Text)
            #elif(algorithm_Text == "Bucket Sort"):
            #  array = funcs.BucketSort(array, entity_Text)
            elif(algorithm_Text == "Radix Sort"):
                array = funcs.RadixSort(array, entity_Text)
            
            
            end_time=time.time()
            runtime=(end_time-start_time)
            self.label_10.setText(str(int(runtime/3600)) + ':' +str(int(runtime/60)) + ':' + str(int(runtime%60)))
            Previous = entity_Text
            
            
        if(category_Text == "RSH E-Shopping Junction" and algorithm_Text != "Select Algorithm" and entity_Text!="Select Entity" and order_Text!='Select Order'):
            row = 0
            self.tableWidget.setColumnCount(9)
            self.tableWidget.setRowCount(len(array))
            self.tableWidget.setHorizontalHeaderLabels(["Type Of Product","Name Of Product","Brand Name","Out Of Stock","Price Of Products","Discount On Product","Delivery Charges","Sold Products","Ratings"])
            if(order_Text == "Increasing"):
                for a in array:
                    self.tableWidget.setItem(row,0,QTableWidgetItem(str(a['Type Of Product'])))
                    self.tableWidget.setItem(row,1,QTableWidgetItem(str(a['Name Of Product'])))
                    self.tableWidget.setItem(row,2,QTableWidgetItem(str(a['Brand Name'])))
                    self.tableWidget.setItem(row,3,QTableWidgetItem(str(a['Out Of Stock'])))
                    self.tableWidget.setItem(row,4,QTableWidgetItem(str(a['Price Of products'])))
                    self.tableWidget.setItem(row,5,QTableWidgetItem(str(a['Discount On Product'])))
                    self.tableWidget.setItem(row,6,QTableWidgetItem(str(a['Delivery Charges'])))
                    self.tableWidget.setItem(row,7,QTableWidgetItem(str(a['Sold Products'])))
                    self.tableWidget.setItem(row,8,QTableWidgetItem(str(a['Ratings'])))
                    row += 1
            elif(order_Text == "Decreasing"):
                for a in range(len(array)-1,-1,-1):
                    self.tableWidget.setItem(row,0,QTableWidgetItem(str(array[a]['Type Of Product'])))
                    self.tableWidget.setItem(row,1,QTableWidgetItem(str(array[a]['Name Of Product'])))
                    self.tableWidget.setItem(row,2,QTableWidgetItem(str(array[a]['Brand Name'])))
                    self.tableWidget.setItem(row,3,QTableWidgetItem(str(array[a]['Out Of Stock'])))
                    self.tableWidget.setItem(row,4,QTableWidgetItem(str(array[a]['Price Of products'])))
                    self.tableWidget.setItem(row,5,QTableWidgetItem(str(array[a]['Discount On Product'])))
                    self.tableWidget.setItem(row,6,QTableWidgetItem(str(array[a]['Delivery Charges'])))
                    self.tableWidget.setItem(row,7,QTableWidgetItem(str(array[a]['Sold Products'])))
                    self.tableWidget.setItem(row,8,QTableWidgetItem(str(array[a]['Ratings'])))
                    row += 1
                
    def load_data(self , array) :
        #self.Searching_tableWidget.clear()
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(len(array))
        print(len(array))
        self.tableWidget.setHorizontalHeaderLabels(["Type Of Product","Name Of Product","Brand Name","Out Of Stock","Price Of Products","Discount On Product","Delivery Charges","Sold Products","Ratings"])
        row = 0
        for a in array:
                self.Searching_tableWidget.setItem(row,0,QTableWidgetItem(str(a['Type Of Product'])))
                self.Searching_tableWidget.setItem(row,1,QTableWidgetItem(str(a['Name Of Product'])))
                self.Searching_tableWidget.setItem(row,2,QTableWidgetItem(str(a['Brand Name'])))
                self.Searching_tableWidget.setItem(row,3,QTableWidgetItem(str(a['Out Of Stock'])))
                self.Searching_tableWidget.setItem(row,4,QTableWidgetItem(str(a['Price Of products'])))
                self.Searching_tableWidget.setItem(row,5,QTableWidgetItem(str(a['Discount On Product'])))
                self.Searching_tableWidget.setItem(row,6,QTableWidgetItem(str(a['Delivery Charges'])))
                self.Searching_tableWidget.setItem(row,7,QTableWidgetItem(str(a['Sold Products'])))
                self.Searching_tableWidget.setItem(row,8,QTableWidgetItem(str(a['Ratings'])))
                row += 1
    def Buttonevent(self):
        array = read_data_from_file.eBay       
        search_text = self.searching_lineEdit.text()
        entity1_text=self.searching_entity1.currentText()
        algorithm_text=self.searching_algorithm.currentText()
        filters_text=self.searching_filters.currentText()
        if(search_text != "Search" and algorithm_text!="Select Algorithm" and entity1_text !='Select Entity' and filters_text !='Filter By' ):
            if filters_text=="Contains" and algorithm_text=="Linear Search":
                array = funcs.LinearSearchthatcontain(array,entity1_text,search_text)
                self.load_data(array)
            elif filters_text=='Starts With' and algorithm_text=="Linear Search":
                    array=funcs.LinearSearchthatStarts(array,entity1_text,search_text)
                    self.load_data(array)
            elif filters_text=='Ends With' and algorithm_text=="Linear Search":
                    array=funcs.LinearSearchthatEnds(array,entity1_text,search_text)
                    self.load_data(array)
            
            
                
        

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
